theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "music"

[[block]]
block = "sound"

[[block]]
block = "bluetooth"
mac = "08:DF:1F:C5:32:A2"

[[block]]
block = "net"
device = "wlp1s0"
ssid = true
signal_strength = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "pacman"
interval = 600

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum} MB"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}Â°"

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 30
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
